name: Manual Approval

on:
  push:
    branches:
      - master

jobs:
  approval-one:
    name: Approval (one)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: One
        run: ./.github/scripts/approval-1.sh

  approval-two:
    name: Approval (two)
    runs-on: ubuntu-latest
    environment: qa
    needs: approval-one

    steps:
      - uses: actions/checkout@v1
      - name: Two
        run: ./.github/scripts/approval-2.sh

  approval-three:
    name: Approval (three)
    runs-on: ubuntu-latest
    environment: prod
    needs: approval-two

    steps:
      - uses: actions/checkout@v1
      - name: Three
        run: ./.github/scripts/approval-3.sh
