name: AWS

on: [push]

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

    steps:
      - uses: actions/checkout@v2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy to bucket
        run: ./scripts/aws-upload.sh
