name: Delete Branch

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch Name'
        required: true

jobs:
  delete-branch:
    name: Delete Branch
    runs-on: ubuntu-latest
    environment: admin
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
      - name: Verify Branch Exists
        run: |
          git fetch

          BRANCH_TEST=$(git ls-remote --heads origin)
          echo "BRANCH_TEST"
          echo "$BRANCH_TEST"

          BRANCH_EXISTS=$(git ls-remote --heads origin ${{github.event.inputs.branch-name}})
          echo "BRANCH_EXISTS"
          echo "$BRANCH_EXISTS"

          if [[ -z ${BRANCH_EXISTS} ]]; then
              echo "Branch does not exist"
              exit 1
          fi

          echo "Branch exists"
          exit 0
      - name: Execute Deletion
        run: |
          git push origin --delete ${{github.event.inputs.branch-name}}
