name: Delete Branch

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch Name'
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - name: Verify Branch Exists
        run: |
          BRANCH_EXISTS=$(git ls-remote --heads origin ${GIT_REF:11})

          echo "$BRANCH_EXISTS"

          if [[ -z ${BRANCH_EXISTS} ]]; then
              echo "Branch does not exist"
              exit 1
          fi

          echo "Branch exists"
          exit 0

  delete-branch:
    name: Delete Branch
    runs-on: ubuntu-latest
    needs: setup
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - run: git push origin --delete ${GIT_REF:11}
