name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      dog:
        description: 'Doggy name'
        required: true
        default: 'Spot'
      pet:
        description: 'Pet dog? (y/n)'
        required: true
        default: 'y'
      virtue:
        description: 'Favorite virtue'
        required: false
        default: ''

jobs:
  manual-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good boy, ${{ github.event.inputs.dog }}!"
      - run: echo "You pet the dog. ${{ github.event.inputs.virtue && 'You think about ' }}${{ github.event.inputs.virtue }}${{ github.event.inputs.virtue && '.' }}"
        if: ${{ github.event.inputs.pet == 'y' }}

  manual-two:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.pet == 'y' }}
    steps:
      - run: echo "You reflect on how great it was to pet the dog."
