name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      dog:
        description: 'Doggy name'
        required: true
        default: 'Spot'
      food:
        description: 'Desired food'
        required: false
        default: 'Gnocci'

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Good boy, ${{ github.event.inputs.dog }}!"
          echo "Gimme ${{ github.event.inputs.food }}."
