name: Operating Systems

on: [push]

jobs:
  os-one:
    name: OS (linux)
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: ./.github/scripts/os.sh

  os-two:
    name: OS (mac)
    runs-on: macos-latest
    needs: os-one

    steps:
      - uses: actions/checkout@v1
      - name: Mac
        run: ./.github/scripts/os.sh

  os-three:
    name: OS (windows)
    runs-on: windows-latest
    needs: os-two

    steps:
      - uses: actions/checkout@v1
      - name: Windows
        shell: bash
        run: ./.github/scripts/os.sh
